/**
 * Automated Quality Reports
 * 
 * Generates and sends automated quality reports
 * Premium feature for Professional and Enterprise tiers
 */

import { licenseManager } from './license-manager';
import { projectHealthAnalyzer } from './project-health';
import { analyticsTracker } from './analytics';

export interface ReportConfig {
  frequency: 'daily' | 'weekly' | 'monthly';
  recipients: string[];
  includeHealthScore: boolean;
  includeAnalytics: boolean;
  includeRecommendations: boolean;
  format: 'markdown' | 'html' | 'json';
}

class AutomatedReporter {
  private schedules: Map<string, ReportConfig> = new Map();

  /**
   * Schedule automated reports
   */
  scheduleReports(projectId: string, config: ReportConfig): void {
    const license = licenseManager.getLicense(projectId);
    
    if (!licenseManager.hasFeature(projectId, 'automated-reports')) {
      throw new Error(
        'Automated reports are a premium feature. Upgrade to Professional or Enterprise tier.'
      );
    }

    this.schedules.set(projectId, config);
    
    // In production, this would set up a cron job or scheduled task
    console.log(`📅 Scheduled ${config.frequency} reports for project ${projectId}`);
  }

  /**
   * Generate report
   */
  async generateReport(projectId: string, config?: ReportConfig): Promise<string> {
    const license = licenseManager.getLicense(projectId);
    
    if (!licenseManager.hasFeature(projectId, 'automated-reports')) {
      throw new Error(
        'Automated reports are a premium feature. Upgrade to Professional or Enterprise tier.'
      );
    }

    const reportConfig = config || this.schedules.get(projectId);
    if (!reportConfig) {
      throw new Error('No report configuration found');
    }

    const sections: string[] = [];

    // Health Score Section
    if (reportConfig.includeHealthScore) {
      try {
        const health = await projectHealthAnalyzer.analyzeProject(projectId);
        sections.push(`## Project Health Score\n\n`);
        sections.push(`**Overall: ${health.overall}/100**\n\n`);
        sections.push(`- Code Quality: ${health.categories.codeQuality}/100\n`);
        sections.push(`- Type Safety: ${health.categories.typeSafety}/100\n`);
        sections.push(`- API Health: ${health.categories.apiHealth}/100\n`);
        sections.push(`- Structure: ${health.categories.structure}/100\n`);
        sections.push(`- Test Coverage: ${health.categories.testCoverage}/100\n\n`);
      } catch (error) {
        sections.push(`## Project Health Score\n\n*Unable to generate health score*\n\n`);
      }
    }

    // Analytics Section
    if (reportConfig.includeAnalytics) {
      const analytics = analyticsTracker.getAnalytics(projectId, 'month');
      if (analytics) {
        sections.push(`## Analytics Summary\n\n`);
        sections.push(`- Validations: ${analytics.validations}\n`);
        sections.push(`- Errors Caught: ${analytics.errorsCaught}\n`);
        sections.push(`- Issues Fixed: ${analytics.issuesFixed}\n`);
        sections.push(`- Time Saved: ${analytics.timeSaved.toFixed(1)} hours\n`);
        sections.push(`- Cost Savings: $${analytics.costSavings.toFixed(2)}\n\n`);
      }
    }

    // Recommendations Section
    if (reportConfig.includeRecommendations) {
      try {
        const health = await projectHealthAnalyzer.analyzeProject(projectId);
        if (health.recommendations.length > 0) {
          sections.push(`## Recommendations\n\n`);
          health.recommendations.forEach((rec) => {
            sections.push(`- ${rec}\n`);
          });
        }
      } catch (error) {
        // Skip if unavailable
      }
    }

    // Format report
    const header = `# Quality Report - ${new Date().toLocaleDateString()}\n\n`;
    const footer = `\n---\n*Generated by AI Agent Guardrails*\n`;

    return header + sections.join('\n') + footer;
  }

  /**
   * Send report
   */
  async sendReport(projectId: string, config?: ReportConfig): Promise<void> {
    const license = licenseManager.getLicense(projectId);
    
    if (!licenseManager.hasFeature(projectId, 'automated-reports')) {
      throw new Error(
        'Automated reports are a premium feature. Upgrade to Professional or Enterprise tier.'
      );
    }

    const report = await this.generateReport(projectId, config);
    const reportConfig = config || this.schedules.get(projectId);

    if (!reportConfig) {
      throw new Error('No report configuration found');
    }

    // In production, this would send emails or webhooks
    console.log(`📧 Sending report to ${reportConfig.recipients.join(', ')}`);
    console.log(`\n${report}\n`);

    // For now, just log
    // In production: await emailService.send(reportConfig.recipients, report);
  }

  /**
   * Get scheduled reports
   */
  getScheduledReports(projectId: string): ReportConfig | null {
    return this.schedules.get(projectId) || null;
  }

  /**
   * Cancel scheduled reports
   */
  cancelReports(projectId: string): void {
    this.schedules.delete(projectId);
    console.log(`❌ Cancelled scheduled reports for project ${projectId}`);
  }
}

export const automatedReporter = new AutomatedReporter();

