/**
 * Context Generator
 * 
 * Generates context files for AI assistants (Cursor, Copilot, Claude, etc.)
 */

import * as fs from 'fs';
import * as path from 'path';
import { ProjectMap, contextManager } from './context-manager';

export interface ContextFile {
  name: string;
  content: string;
  format: 'markdown' | 'json' | 'yaml' | 'txt';
  target: 'cursor' | 'copilot' | 'claude' | 'universal';
}

class ContextGenerator {
  /**
   * Generate all context files for AI assistants
   */
  async generateAll(projectMap: ProjectMap, outputDir: string = '.guardrail'): Promise<ContextFile[]> {
    await fs.promises.mkdir(outputDir, { recursive: true });

    const files: ContextFile[] = [];

    // Universal context file
    files.push(await this.generateUniversalContext(projectMap, outputDir));

    // Cursor-specific
    files.push(await this.generateCursorContext(projectMap, outputDir));

    // Copilot-specific
    files.push(await this.generateCopilotContext(projectMap, outputDir));

    // Claude-specific
    files.push(await this.generateClaudeContext(projectMap, outputDir));

    // Rules file
    files.push(await this.generateRulesFile(projectMap, outputDir));

    // Project map
    files.push(await this.generateProjectMap(projectMap, outputDir));

    return files;
  }

  /**
   * Generate universal context file
   */
  private async generateUniversalContext(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const content = await contextManager.generateAIContextFile(projectMap);
    const filePath = path.join(outputDir, 'context.json');

    await fs.promises.writeFile(filePath, content);

    return {
      name: 'context.json',
      content,
      format: 'json',
      target: 'universal',
    };
  }

  /**
   * Generate Cursor-specific context (.cursorrules)
   */
  private async generateCursorContext(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const rules = await contextManager.generateContextRules(projectMap);
    
    const cursorContent = `# guardrail AI - Full Codebase Context

This file is automatically generated by guardrail AI to provide your AI assistant with complete project awareness.

${rules}

## How to Use

This context file is automatically loaded by Cursor. The AI assistant now has full awareness of:
- Your project architecture
- All API endpoints
- Data structures and models
- Code patterns and conventions
- Dependencies and connections

When generating code, the AI will:
1. Follow your established patterns
2. Use correct naming conventions
3. Match your architecture
4. Reference real endpoints
5. Follow your file structure

## Updating Context

Run \`guardrail context\` to regenerate this file when your codebase changes.
`;

    const filePath = path.join(outputDir, '.cursorrules');
    await fs.promises.writeFile(filePath, cursorContent);

    return {
      name: '.cursorrules',
      content: cursorContent,
      format: 'markdown',
      target: 'cursor',
    };
  }

  /**
   * Generate Copilot-specific context
   */
  private async generateCopilotContext(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const content = `# guardrail AI Context for GitHub Copilot

## Project Overview
- Type: ${projectMap.architecture.type}
- Framework: ${projectMap.metadata.framework || 'Unknown'}
- Total Files: ${projectMap.metadata.totalFiles}
- Languages: ${projectMap.metadata.languages.join(', ')}

## Key Endpoints
${projectMap.endpoints.slice(0, 20).map(ep => `- ${ep.method} ${ep.path}`).join('\n')}

## Data Structures
${projectMap.dataStructures.slice(0, 20).map(ds => `- ${ds.name}: ${ds.fields.map(f => f.name).join(', ')}`).join('\n')}

## Conventions
- Files: ${projectMap.conventions.naming.files}
- Components: ${projectMap.conventions.naming.components}
- Functions: ${projectMap.conventions.naming.functions}
`;

    const filePath = path.join(outputDir, 'copilot-context.md');
    await fs.promises.writeFile(filePath, content);

    return {
      name: 'copilot-context.md',
      content,
      format: 'markdown',
      target: 'copilot',
    };
  }

  /**
   * Generate Claude-specific context
   */
  private async generateClaudeContext(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const content = JSON.stringify({
      project: {
        name: path.basename(process.cwd()),
        architecture: projectMap.architecture,
        conventions: projectMap.conventions,
      },
      endpoints: projectMap.endpoints,
      dataStructures: projectMap.dataStructures,
      patterns: projectMap.patterns,
    }, null, 2);

    const filePath = path.join(outputDir, 'claude-context.json');
    await fs.promises.writeFile(filePath, content);

    return {
      name: 'claude-context.json',
      content,
      format: 'json',
      target: 'claude',
    };
  }

  /**
   * Generate rules file
   */
  private async generateRulesFile(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const content = await contextManager.generateContextRules(projectMap);
    const filePath = path.join(outputDir, 'rules.md');

    await fs.promises.writeFile(filePath, content);

    return {
      name: 'rules.md',
      content,
      format: 'markdown',
      target: 'universal',
    };
  }

  /**
   * Generate project map file
   */
  private async generateProjectMap(
    projectMap: ProjectMap,
    outputDir: string
  ): Promise<ContextFile> {
    const content = JSON.stringify(projectMap, null, 2);
    const filePath = path.join(outputDir, 'project-map.json');

    await fs.promises.writeFile(filePath, content);

    return {
      name: 'project-map.json',
      content,
      format: 'json',
      target: 'universal',
    };
  }

  /**
   * Generate IDE-specific integration files
   */
  async generateIDEIntegration(outputDir: string = '.guardrail'): Promise<void> {
    // VSCode settings
    const vscodeDir = path.join(outputDir, '.vscode');
    await fs.promises.mkdir(vscodeDir, { recursive: true });

    const settings = {
      'files.associations': {
        '.cursorrules': 'markdown',
      },
      'editor.defaultFormatter': 'esbenp.prettier-vscode',
    };

    await fs.promises.writeFile(
      path.join(vscodeDir, 'settings.json'),
      JSON.stringify(settings, null, 2)
    );

    // Cursor settings
    const cursorSettings = {
      'cursor.general.enableContext': true,
      'cursor.general.contextFile': '.guardrail/.cursorrules',
    };

    await fs.promises.writeFile(
      path.join(outputDir, 'cursor-settings.json'),
      JSON.stringify(cursorSettings, null, 2)
    );
  }
}

export const contextGenerator = new ContextGenerator();

