import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Code Hallucination (Definition + Detection Signals)",
  description:
    "Definition: AI code hallucination and the practical detection signals that catch fabricated APIs, placeholder logic, and fake behavior before deploy.",
};

// Static page - revalidate every hour
export const revalidate = 3600;

export default function AICodeHallucinationGlossaryPage() {
  return (
    <article className="prose prose-slate max-w-4xl mx-auto py-12 px-4">
      <h1>AI code hallucination</h1>

      <p>
        An <strong>AI code hallucination</strong> is code generated by an LLM
        that appears valid but contains fabricated logic, APIs, or assumptions
        that fail at runtime.
      </p>

      <h2>Why it's dangerous</h2>

      <ul>
        <li>it compiles and can pass shallow tests</li>
        <li>it looks "reasonable," so it survives review</li>
        <li>it often fails silently (fake fallbacks, plausible objects)</li>
      </ul>

      <h2>Practical detection signals</h2>

      <ul>
        <li>placeholder branches and "temporary" stubs in production paths</li>
        <li>imports that don't exist or don't match your internal APIs</li>
        <li>
          hardcoded or generic data objects returned in lieu of real calls
        </li>
        <li>missing env vars that trigger fake fallbacks</li>
      </ul>

      <h2>Prevention</h2>

      <p>
        Use a gate that checks reality boundaries: endpoint wiring, auth
        coverage, required env vars, and mock/stub imports in production builds.
      </p>

      <p>Some teams use guardrail to detect this automatically in CI.</p>
    </article>
  );
}
