/**
 * CI/CD Generator Functions
 * Generates GitHub Actions workflows and git hooks for guardrail integration
 */

// Basic interface for guardrail config
interface GuardrailConfig {
  output?: {
    sarifUpload?: boolean;
    format?: string;
  };
  scans?: {
    secrets?: { enabled?: boolean };
    vulnerabilities?: { enabled?: boolean };
    compliance?: { enabled?: boolean };
  };
}

/**
 * Generate GitHub Actions workflow for guardrail
 */
export function generateGitHubActions(config: GuardrailConfig): string {
  const sarifEnabled = config.output?.sarifUpload || false;
  
  const workflowSteps = sarifEnabled ? `
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run guardrail scan
      run: npx guardrail scan --format sarif --output results.sarif
      env:
        GUARDRAIL_API_KEY: \${{ secrets.GUARDRAIL_API_KEY }}
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif` : `
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run guardrail scan
      run: npx guardrail scan
      env:
        GUARDRAIL_API_KEY: \${{ secrets.GUARDRAIL_API_KEY }}`;

  return `# GitHub Actions workflow for guardrail
# Auto-generated by guardrail CLI
name: guardrail Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:${workflowSteps}
`;
}

/**
 * Generate pre-commit hooks for guardrail
 */
export function generatePreCommitHooks(_config: GuardrailConfig): string {
  return `#!/bin/sh
# Pre-commit hook for guardrail security scan
# Auto-generated by guardrail CLI

echo "Running guardrail pre-commit scan..."

# Run guardrail scan on staged files
npx guardrail scan --staged --format table

# Check exit code
if [ $? -ne 0 ]; then
    echo "❌ guardrail scan failed. Commit blocked."
    echo "Fix the security issues or use --no-verify to bypass."
    exit 1
fi

echo "✅ guardrail scan passed. Proceeding with commit."
exit 0
`;
}

/**
 * Generate GitLab CI configuration
 */
export function generateGitLabCI(_config: GuardrailConfig): string {
  return `# GitLab CI configuration for guardrail
# Auto-generated by guardrail CLI

stages:
  - security

guardrail_scan:
  stage: security
  image: node:18
  before_script:
    - npm ci
  script:
    - npx guardrail scan --format table
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  artifacts:
    reports:
      security: results.sarif
    paths:
      - results.sarif
  variables:
    GUARDRAIL_API_KEY: $GUARDRAIL_API_KEY
`;
}

/**
 * Generate Azure DevOps pipeline
 */
export function generateAzurePipeline(_config: GuardrailConfig): string {
  return `# Azure DevOps pipeline for guardrail
# Auto-generated by guardrail CLI

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npx guardrail scan --format table
  displayName: 'Run guardrail scan'
  env:
    GUARDRAIL_API_KEY: $(GUARDRAIL_API_KEY)

- task: PublishSecurityAnalysisLogs@1
  condition: succeededOrFailed()
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
`;
}

/**
 * Generate Bitbucket Pipes configuration
 */
export function generateBitbucketPipes(_config: GuardrailConfig): string {
  return `# Bitbucket Pipelines configuration for guardrail
# Auto-generated by guardrail CLI

pipelines:
  default:
    - step:
        name: 'guardrail Security Scan'
        image: node:18
        caches:
          - npm
        script:
          - npm ci
          - npx guardrail scan --format table
        artifacts:
          - results.sarif*

  branches:
    main:
      - step:
          name: 'guardrail Security Scan'
          image: node:18
          caches:
            - npm
          script:
            - npm ci
            - npx guardrail scan --format table
          artifacts:
            - results.sarif*

definitions:
  services:
    docker:
      memory: 2048
`;
}
