/**
 * Reality Explorer - Auto-generated Playwright Test
 * 
 * This test ACTUALLY explores your app:
 * - Visits every discoverable route
 * - Clicks every safe button and element  
 * - Fills and submits forms
 * - Captures what works and what breaks
 * 
 * Generated by guardrail Reality Mode
 * Target: https://guardrailai.dev
 * Generated: 2026-01-05T05:08:13.506Z
 */

import { test, expect, Page, BrowserContext } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Configuration
const CONFIG = {
  baseUrl: 'https://guardrailai.dev',
  outputDir: 'C:\\Users\\mevla\\Downloads\\codeguard(1)\\codeguard\\.guardrail\\reality',
  timeout: 30000,
  allowDestructive: false,
  maxActionsPerPage: 50,
  maxPages: 20,
};

// Test data for form filling
const TEST_DATA = {
  email: 'test-reality@guardrailai.dev',
  password: 'TestPass123!',
  name: 'Reality Test User',
  phone: '+1234567890',
  address: '123 Test Street',
  city: 'Test City',
  zip: '12345',
  text: 'Test input from guardrail Reality Mode',
  number: '42',
  url: 'https://example.com',
  date: '2024-01-15',
};

// Destructive action patterns to avoid
const DESTRUCTIVE_PATTERNS = [
  /delete/i, /remove/i, /destroy/i, /cancel.*subscription/i,
  /deactivate/i, /terminate/i, /close.*account/i, /reset.*all/i,
];

// Results storage
interface ExplorerResults {
  routes: { path: string; status: string; error?: string; responseTime?: number }[];
  elements: { selector: string; text: string; status: string; error?: string; changes: string[] }[];
  forms: { selector: string; status: string; error?: string; fieldsFilledCount: number }[];
  errors: { type: string; message: string; url: string; timestamp: number }[];
  networkCalls: { url: string; method: string; status: number }[];
  coverage: { routes: number; elements: number; forms: number };
  score: number;
  duration: number;
}

const results: ExplorerResults = {
  routes: [],
  elements: [],
  forms: [],
  errors: [],
  networkCalls: [],
  coverage: { routes: 0, elements: 0, forms: 0 },
  score: 0,
  duration: 0,
};

let discoveredRoutes: string[] = [];
let discoveredElements: any[] = [];
let discoveredForms: any[] = [];
let startTime: number;

test.describe('Reality Explorer', () => {
  let context: BrowserContext;
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    startTime = Date.now();
    
    // Create context with video recording
    context = await browser.newContext({
      viewport: { width: 1280, height: 720 },
      recordVideo: { dir: path.join(CONFIG.outputDir, 'videos') },
    });
    
    await context.tracing.start({ screenshots: true, snapshots: true });
    page = await context.newPage();
    
    // Capture console errors
    page.on('console', msg => {
      if (msg.type() === 'error') {
        results.errors.push({
          type: 'console',
          message: msg.text().slice(0, 200),
          url: page.url(),
          timestamp: Date.now(),
        });
      }
    });
    
    // Capture uncaught errors
    page.on('pageerror', error => {
      results.errors.push({
        type: 'uncaught',
        message: error.message.slice(0, 200),
        url: page.url(),
        timestamp: Date.now(),
      });
    });
    
    // Capture API calls
    page.on('response', async response => {
      const url = response.url();
      if (url.includes('/api/') || url.includes('/graphql') || url.includes('/_next/data')) {
        results.networkCalls.push({
          url: url.split('?')[0],
          method: response.request().method(),
          status: response.status(),
        });
      }
    });
    
    if (!fs.existsSync(CONFIG.outputDir)) {
      fs.mkdirSync(CONFIG.outputDir, { recursive: true });
    }
  });

  test.afterAll(async () => {
    results.duration = Date.now() - startTime;
    
    await context.tracing.stop({ 
      path: path.join(CONFIG.outputDir, 'trace.zip') 
    });
    
    results.score = calculateScore(results);
    
    fs.writeFileSync(
      path.join(CONFIG.outputDir, 'explorer-results.json'),
      JSON.stringify(results, null, 2)
    );
    
    const html = generateHTMLReport(results);
    fs.writeFileSync(path.join(CONFIG.outputDir, 'reality-report.html'), html);
    
    await context.close();
    
    // Print summary to console
    console.log('\n' + '='.repeat(60));
    console.log('  REALITY MODE COMPLETE');
    console.log('='.repeat(60));
    console.log(`  Score: ${results.score}/100`);
    console.log(`  Routes: ${results.coverage.routes}/${results.routes.length} working`);
    console.log(`  Elements: ${results.coverage.elements}/${results.elements.length} working`);
    console.log(`  Forms: ${results.coverage.forms}/${results.forms.length} working`);
    console.log(`  Errors: ${results.errors.length} captured`);
    console.log(`  Duration: ${(results.duration / 1000).toFixed(1)}s`);
    console.log('='.repeat(60));
    console.log(`  Report: ${path.join(CONFIG.outputDir, 'reality-report.html')}`);
    console.log('='.repeat(60) + '\n');
  });

  // Enhanced authentication flows
  test('00 - Test Signup Flow', async () => {
    await page.goto(CONFIG.baseUrl);
    await page.waitForLoadState('networkidle');
    
    // Look for signup/register buttons
    const signupSelectors = [
      'button:has-text("Sign Up")',
      'button:has-text("Create Account")', 
      'button:has-text("Register")',
      'a:has-text("Sign Up")',
      '[data-testid="signup"]',
      '[data-testid="register"]'
    ];
    
    let signupButton = null;
    for (const selector of signupSelectors) {
      try {
        signupButton = await page.$(selector);
        if (signupButton && await signupButton.isVisible()) {
          console.log(`✅ Found signup button: ${selector}`);
          break;
        }
      } catch (e) {}
    }
    
    if (signupButton) {
      await signupButton.click();
      await page.waitForLoadState('networkidle');
      
      // Fill signup form with test data
      const emailField = await page.$('input[type="email"], input[name="email"], #email');
      const passwordField = await page.$('input[type="password"], input[name="password"], #password');
      const nameField = await page.$('input[name="name"], input[name="fullName"], #name');
      
      if (emailField) await emailField.fill(`test-${Date.now()}@guardrailai.dev`);
      if (nameField) await nameField.fill('Reality Test User');
      if (passwordField) await passwordField.fill('TestPass123!');
      
      // Submit form
      const submitButton = await page.$('button[type="submit"], button:has-text("Sign Up"), button:has-text("Create")');
      if (submitButton) {
        await submitButton.click();
        await page.waitForLoadState('networkidle');
        
        // Check if we're redirected to dashboard or get success message
        const currentUrl = page.url();
        const hasDashboard = currentUrl.includes('/dashboard') || currentUrl.includes('/app') || currentUrl.includes('/home');
        
        results.forms.push({
          selector: 'signup-form',
          status: hasDashboard ? 'success' : 'attempted',
          fieldsFilledCount: [emailField, passwordField, nameField].filter(Boolean).length,
        });
        
        console.log(hasDashboard ? '✅ Signup successful - redirected to dashboard' : '⚠️ Signup attempted');
      }
    } else {
      console.log('ℹ️ No signup button found');
    }
  });

  test('01 - Test Login Flow', async () => {
    await page.goto(CONFIG.baseUrl);
    await page.waitForLoadState('networkidle');
    
    // Look for login buttons
    const loginSelectors = [
      'button:has-text("Login")',
      'button:has-text("Sign In")',
      'a:has-text("Login")',
      '[data-testid="login"]',
      '[data-testid="signin"]'
    ];
    
    let loginButton = null;
    for (const selector of loginSelectors) {
      try {
        loginButton = await page.$(selector);
        if (loginButton && await loginButton.isVisible()) {
          console.log(`✅ Found login button: ${selector}`);
          break;
        }
      } catch (e) {}
    }
    
    if (loginButton) {
      await loginButton.click();
      await page.waitForLoadState('networkidle');
      
      // Fill login form
      const emailField = await page.$('input[type="email"], input[name="email"], #email');
      const passwordField = await page.$('input[type="password"], input[name="password"], #password');
      
      if (emailField) await emailField.fill('test@guardrailai.dev');
      if (passwordField) await passwordField.fill('TestPass123!');
      
      // Submit form
      const submitButton = await page.$('button[type="submit"], button:has-text("Login"), button:has-text("Sign In")');
      if (submitButton) {
        await submitButton.click();
        await page.waitForLoadState('networkidle');
        
        // Check for dashboard or error
        const currentUrl = page.url();
        const hasDashboard = currentUrl.includes('/dashboard') || currentUrl.includes('/app') || currentUrl.includes('/home');
        const hasError = await page.$('text=Invalid credentials, text=Error, text=Failed');
        
        results.forms.push({
          selector: 'login-form',
          status: hasDashboard ? 'success' : hasError ? 'error' : 'attempted',
          fieldsFilledCount: [emailField, passwordField].filter(Boolean).length,
        });
        
        console.log(hasDashboard ? '✅ Login successful' : hasError ? '❌ Login failed' : '⚠️ Login attempted');
      }
    } else {
      console.log('ℹ️ No login button found');
    }
  });

  

  test('02 - Discover App Surface', async () => {
    await page.goto(CONFIG.baseUrl);
    await page.waitForLoadState('networkidle');
    
    // Take initial screenshot
    await page.screenshot({ path: path.join(CONFIG.outputDir, 'home.png') });
    
    // Enhanced route discovery for SPAs
    discoveredRoutes = await page.evaluate(() => {
      const routes = new Set<string>();
      
      // Get all link hrefs
      document.querySelectorAll('a[href]').forEach(anchor => {
        const href = anchor.getAttribute('href');
        if (href && href.startsWith('/') && !href.startsWith('//') && !href.includes('#')) {
          routes.add(href);
        }
      });
      
      // Look for data-route attributes
      document.querySelectorAll('[data-route]').forEach(el => {
        const route = el.getAttribute('data-route');
        if (route) routes.add(route.startsWith('/') ? route : '/' + route);
      });
      
      // Look for common SPA route patterns
      const commonRoutes = ['/dashboard', '/app', '/account', '/settings', '/profile', '/projects', '/analytics'];
      commonRoutes.forEach(route => routes.add(route));
      
      return Array.from(routes);
    });
    
    // Also try to find navigation menus and extract routes
    const navRoutes = await page.evaluate(() => {
      const routes = new Set<string>();
      
      // Check navigation menus
      document.querySelectorAll('nav a, .nav a, .navigation a, .menu a').forEach(anchor => {
        const href = anchor.getAttribute('href');
        if (href && href.startsWith('/') && !href.includes('#') && !href.includes('http')) {
          routes.add(href);
        }
      });
      
      return Array.from(routes);
    });
    
    // Merge all discovered routes
    discoveredRoutes = [...new Set([...discoveredRoutes, ...navRoutes])];
    
    console.log(`📍 Discovered ${discoveredRoutes.length} routes`);
    
    // Discover interactive elements
    discoveredElements = await page.$$eval(
      'button, [role="button"], input[type="submit"], [data-testid]',
      (elements: Element[]) => elements.map((el, idx) => {
        const text = el.textContent?.trim().slice(0, 50) || '';
        return {
          selector: el.id ? `#${el.id}` : 
                    el.getAttribute('data-testid') ? `[data-testid="${el.getAttribute('data-testid')}"]` :
                    `button:nth-of-type(${idx + 1})`,
          text,
          type: el.tagName.toLowerCase(),
          isDestructive: /delete|remove|destroy|cancel|deactivate/i.test(text),
        };
      }).filter(el => el.text.length > 0)
    );
    
    console.log(`🔘 Discovered ${discoveredElements.length} interactive elements`);
    
    // Discover forms
    discoveredForms = await page.$$eval('form', (forms: HTMLFormElement[]) => 
      forms.map((form, idx) => ({
        selector: form.id ? `#${form.id}` : `form:nth-of-type(${idx + 1})`,
        fields: Array.from(form.querySelectorAll('input, textarea, select')).map((field: any) => ({
          name: field.name || field.id || 'unknown',
          type: field.type || 'text',
          required: field.required,
        })),
      }))
    );
    
    console.log(`📝 Discovered ${discoveredForms.length} forms`);
  });

  test('03 - Visit All Routes', async () => {
    const routesToVisit = discoveredRoutes.slice(0, CONFIG.maxPages);
    
    for (const route of routesToVisit) {
      const startTime = Date.now();
      
      try {
        const response = await page.goto(CONFIG.baseUrl + route, { 
          waitUntil: 'networkidle',
          timeout: CONFIG.timeout 
        });
        
        const status = response?.status() || 0;
        const responseTime = Date.now() - startTime;
        
        results.routes.push({
          path: route,
          status: status >= 200 && status < 400 ? 'success' : 'error',
          responseTime,
          error: status >= 400 ? `HTTP ${status}` : undefined,
        });
        
        // Re-discover elements on each page
        const pageElements = await page.$$eval(
          'button, [role="button"], input[type="submit"]',
          (elements: Element[]) => elements.map((el, idx) => ({
            selector: el.id ? `#${el.id}` : `button:nth-of-type(${idx + 1})`,
            text: el.textContent?.trim().slice(0, 50) || '',
            type: el.tagName.toLowerCase(),
            isDestructive: /delete|remove|destroy/i.test(el.textContent || ''),
            page: '',
          })).filter(el => el.text.length > 0)
        );
        
        for (const el of pageElements) {
          if (!discoveredElements.find((e: any) => e.selector === el.selector)) {
            discoveredElements.push({ ...el, page: route });
          }
        }
        
      } catch (error: any) {
        results.routes.push({
          path: route,
          status: 'error',
          error: error.message.slice(0, 100),
        });
      }
    }
    
    results.coverage.routes = results.routes.filter(r => r.status === 'success').length;
    console.log(`✅ Visited ${results.coverage.routes}/${routesToVisit.length} routes`);
  });

  test('04 - Test Dashboard Functionality', async () => {
    // Try to find and access dashboard
    const dashboardSelectors = [
      '/dashboard',
      '/app', 
      '/home',
      '/account',
      '/profile'
    ];
    
    let dashboardFound = false;
    
    for (const dashboardPath of dashboardSelectors) {
      try {
        const response = await page.goto(CONFIG.baseUrl + dashboardPath, { 
          waitUntil: 'networkidle',
          timeout: 10000 
        });
        
        if (response && response.status() === 200) {
          const hasDashboardContent = await page.$('text=Dashboard, text=Overview, text=Analytics, text=Projects, text=Settings');
          if (hasDashboardContent) {
            dashboardFound = true;
            console.log(`✅ Dashboard found at ${dashboardPath}`);
            
            // Test dashboard functionality
            await testDashboardFeatures(page, dashboardPath);
            break;
          }
        }
      } catch (e) {
        // Continue to next dashboard path
      }
    }
    
    if (!dashboardFound) {
      console.log('ℹ️ No accessible dashboard found');
    }
  });

  test('05 - Test Interactive Elements', async () => {
    await page.goto(CONFIG.baseUrl);
    await page.waitForLoadState('networkidle');
    
    const elementsToTest = discoveredElements
      .filter((el: any) => !el.isDestructive || CONFIG.allowDestructive)
      .slice(0, CONFIG.maxActionsPerPage);
    
    for (const element of elementsToTest) {
      const result = await testElement(page, element);
      results.elements.push(result);
    }
    
    results.coverage.elements = results.elements.filter(e => e.status === 'success').length;
    console.log(`✅ Tested ${results.coverage.elements}/${elementsToTest.length} elements`);
  });

  test('06 - Test Forms', async () => {
    await page.goto(CONFIG.baseUrl);
    await page.waitForLoadState('networkidle');
    
    for (const form of discoveredForms) {
      const result = await testForm(page, form);
      results.forms.push(result);
    }
    
    results.coverage.forms = results.forms.filter(f => f.status === 'success').length;
    console.log(`✅ Tested ${results.coverage.forms}/${discoveredForms.length} forms`);
  });
});

// Test dashboard features
async function testDashboardFeatures(page: Page, dashboardPath: string) {
  try {
    // Look for common dashboard elements
    const dashboardFeatures = [
      { selector: 'text=Projects', name: 'Projects section' },
      { selector: 'text=Analytics', name: 'Analytics section' },
      { selector: 'text=Settings', name: 'Settings section' },
      { selector: 'text=Overview', name: 'Overview section' },
      { selector: 'text=Reports', name: 'Reports section' },
      { selector: 'text=Activity', name: 'Activity section' },
      { selector: 'text=Profile', name: 'Profile section' },
      { selector: 'text=Account', name: 'Account section' }
    ];
    
    for (const feature of dashboardFeatures) {
      try {
        const element = await page.$(feature.selector);
        if (element && await element.isVisible()) {
          console.log(`  ✓ ${feature.name} found`);
          
          // Try to interact with it
          await element.click({ timeout: 3000 });
          await page.waitForTimeout(1000);
          
          // Check if something changed
          const currentUrl = page.url();
          if (currentUrl !== page.url()) {
            console.log(`    → Navigation successful`);
            await page.goBack().catch(() => {});
          }
        }
      } catch (e) {
        console.log(`  ⚠️ ${feature.name} not accessible`);
      }
    }
    
    // Look for data tables or lists
    const dataElements = await page.$('table, .table, [role="grid"], .list, .data-grid');
    if (dataElements) {
      console.log(`  ✓ Data display elements found`);
    }
    
    // Look for charts or graphs
    const chartElements = await page.$('canvas, .chart, .graph, [data-chart]');
    if (chartElements) {
      console.log(`  ✓ Chart/graph elements found`);
    }
    
    // Look for action buttons
    const actionButtons = await page.$$('button:has-text("Create"), button:has-text("Add"), button:has-text("New"), button:has-text("Edit")');
    if (actionButtons.length > 0) {
      console.log(`  ✓ ${actionButtons.length} action buttons found`);
    }
    
async function testElement(page: Page, element: any) {
  const beforeUrl = page.url();
  const changes: string[] = [];
  
  try {
    // Wait for element to be ready with multiple strategies
    let el = await page.$(element.selector);
    if (!el) {
      return { selector: element.selector, text: element.text, status: 'not-found', changes: [] };
    }
    
    // Wait for element to be visible and stable
    try {
      await el.waitFor({ state: 'visible', timeout: 3000 });
    } catch (e) {
      // Element might not be visible, try scrolling to it
      await el.scrollIntoViewIfNeeded();
      await page.waitForTimeout(500);
    }
    
    // Check visibility again after scrolling
    const isVisible = await el.isVisible().catch(() => false);
    if (!isVisible) {
      return { selector: element.selector, text: element.text, status: 'hidden', changes: [] };
    }
    
    // Ensure element is in viewport and not obscured
    await el.scrollIntoViewIfNeeded();
    await page.waitForTimeout(300);
    
    // Try multiple interaction strategies
    let interactionSuccess = false;
    const strategies = [
      // Standard click
      async () => {
        await el.click({ timeout: 5000 });
        return true;
      },
      // Click with force
      async () => {
        await el.click({ force: true, timeout: 3000 });
        return true;
      },
      // Hover then click
      async () => {
        await el.hover();
        await page.waitForTimeout(200);
        await el.click();
        return true;
      },
      // Double click
      async () => {
        await el.dblclick();
        return true;
      }
    ];
    
    for (const strategy of strategies) {
      try {
        await strategy();
        interactionSuccess = true;
        break;
      } catch (e) {
        continue; // Try next strategy
      }
    }
    
    if (!interactionSuccess) {
      return { 
        selector: element.selector, 
        text: element.text, 
        status: 'no-interaction', 
        changes: [] 
      };
    }
    
    // Wait for any async updates after interaction
    await page.waitForTimeout(500);
    
    // Check for various types of changes
    const afterUrl = page.url();
    if (afterUrl !== beforeUrl) {
      changes.push('URL: ' + afterUrl);
    }
    
    // Check for modals, popups, or overlays
    const modalSelectors = [
      '[role="dialog"]', 
      '.modal', 
      '[data-state="open"]',
      '.popup',
      '.overlay',
      '.dropdown-menu'
    ];
    
    for (const modalSelector of modalSelectors) {
      const modal = await page.$(modalSelector);
      if (modal && await modal.isVisible()) {
        changes.push('Modal opened: ' + modalSelector);
        // Try to close modal to continue testing
        await page.keyboard.press('Escape');
        await page.waitForTimeout(300);
        break;
      }
    }
    
    // Check for dynamic content changes
    const contentChanged = await page.evaluate((beforeUrl) => {
      const body = document.body;
      if (!body) return false;
      
      // Look for loading indicators that disappeared
      const loadingElements = document.querySelectorAll('[data-loading], .loading, .spinner');
      const hasLoading = loadingElements.length > 0;
      
      // Look for new content that appeared
      const newContent = document.querySelectorAll('[data-loaded], .loaded, .content');
      const hasNewContent = newContent.length > 0;
      
      return hasLoading || hasNewContent;
    }, beforeUrl);
    
    if (contentChanged) {
      changes.push('Dynamic content updated');
    }
    
    // Check for form validation or error messages
    const validationMessages = await page.$$eval(
      '.error, .validation-error, [data-error], .invalid',
      (elements) => elements.map(el => el.textContent?.trim()).filter(Boolean)
    );
    
    if (validationMessages.length > 0) {
      changes.push('Validation: ' + validationMessages[0]);
    }
    
    // Check for success messages
    const successMessages = await page.$$eval(
      '.success, .valid, [data-success], .confirmation',
      (elements) => elements.map(el => el.textContent?.trim()).filter(Boolean)
    );
    
    if (successMessages.length > 0) {
      changes.push('Success: ' + successMessages[0]);
    }
    
    return {
      selector: element.selector,
      text: element.text,
      status: changes.length > 0 ? 'success' : 'no-change',
      changes,
    };
    
  } catch (error: any) {
    return {
      selector: element.selector,
      text: element.text,
      status: 'error',
      error: error.message.slice(0, 100),
      changes: [],
    };
  }
}

// Test a form
async function testForm(page: Page, form: any) {
  let fieldsFilledCount = 0;
  
  try {
    const formEl = await page.$(form.selector);
    if (!formEl) {
      return { selector: form.selector, status: 'not-found', fieldsFilledCount: 0 };
    }
    
    for (const field of form.fields) {
      try {
        const value = getTestValue(field.type, field.name);
        const fieldEl = await formEl.$(`[name="${field.name}"], #${field.name}`);
        
        if (fieldEl) {
          if (field.type === 'checkbox' || field.type === 'radio') {
            await fieldEl.check().catch(() => {});
          } else {
            await fieldEl.fill(value);
          }
          fieldsFilledCount++;
        }
      } catch (e) {}
    }
    
    return {
      selector: form.selector,
      status: fieldsFilledCount > 0 ? 'success' : 'no-fields',
      fieldsFilledCount,
    };
    
  } catch (error: any) {
    return {
      selector: form.selector,
      status: 'error',
      error: error.message.slice(0, 100),
      fieldsFilledCount,
    };
  }
}

// Get test value for field
function getTestValue(type: string, name: string): string {
  const n = name?.toLowerCase() || '';
  if (n.includes('email')) return TEST_DATA.email;
  if (n.includes('password')) return TEST_DATA.password;
  if (n.includes('phone')) return TEST_DATA.phone;
  if (n.includes('name')) return TEST_DATA.name;
  if (type === 'email') return TEST_DATA.email;
  if (type === 'password') return TEST_DATA.password;
  if (type === 'number') return TEST_DATA.number;
  return TEST_DATA.text;
}

// Calculate score
function calculateScore(results: ExplorerResults): number {
  const tr = results.routes.length || 1;
  const te = results.elements.length || 1;
  const tf = results.forms.length || 1;
  
  const routeScore = (results.coverage.routes / tr) * 15;
  const elemScore = (results.coverage.elements / te) * 15;
  const formScore = (results.coverage.forms / tf) * 10;
  const coverage = routeScore + elemScore + formScore;
  
  const funcScore = 
    ((results.elements.filter(e => e.status === 'success').length / te) * 20) +
    ((results.forms.filter(f => f.status === 'success').length / tf) * 15);
  
  const errorPenalty = Math.min(results.errors.length * 3, 15);
  const stability = 15 - errorPenalty;
  
  const interactive = results.elements.filter(e => e.changes?.length > 0).length;
  const ux = Math.min((interactive / te) * 10, 10);
  
  return Math.round(Math.max(0, Math.min(100, coverage + funcScore + stability + ux)));
}

// Generate HTML report
function generateHTMLReport(results: ExplorerResults): string {
  const score = results.score;
  const grade = score >= 90 ? 'A' : score >= 80 ? 'B' : score >= 70 ? 'C' : score >= 60 ? 'D' : 'F';
  const color = score >= 80 ? '#22c55e' : score >= 60 ? '#eab308' : '#ef4444';
  const verdict = score >= 80 ? '✅ Ready to ship!' : score >= 60 ? '⚠️ Needs work' : '❌ Critical issues';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Reality Mode Report - guardrail</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #fff; padding: 2rem; line-height: 1.5; }
    .container { max-width: 1000px; margin: 0 auto; }
    h1 { font-size: 1.75rem; margin-bottom: 0.25rem; display: flex; align-items: center; gap: 0.5rem; }
    .subtitle { color: #888; margin-bottom: 2rem; font-size: 0.875rem; }
    .score-card { background: linear-gradient(135deg, #1a1a2e, #16213e); border: 1px solid #333; border-radius: 1rem; padding: 2rem; text-align: center; margin-bottom: 2rem; }
    .score { font-size: 5rem; font-weight: 800; color: ${color}; line-height: 1; }
    .grade { font-size: 1.5rem; color: ${color}; margin-top: 0.5rem; }
    .verdict { color: #ccc; margin-top: 0.5rem; }
    .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .metric { background: #1a1a1a; border: 1px solid #333; border-radius: 0.75rem; padding: 1.25rem; text-align: center; }
    .metric-value { font-size: 1.75rem; font-weight: 700; color: #fff; }
    .metric-label { color: #888; font-size: 0.75rem; margin-top: 0.25rem; }
    .section { background: #111; border: 1px solid #222; border-radius: 0.75rem; margin-bottom: 1rem; overflow: hidden; }
    .section-header { background: #1a1a1a; padding: 1rem 1.25rem; font-weight: 600; display: flex; align-items: center; gap: 0.5rem; border-bottom: 1px solid #222; }
    .section-content { padding: 0.5rem 0; max-height: 400px; overflow-y: auto; }
    .item { display: flex; justify-content: space-between; align-items: center; padding: 0.75rem 1.25rem; border-bottom: 1px solid #1a1a1a; }
    .item:last-child { border-bottom: none; }
    .item-name { font-size: 0.875rem; color: #ddd; max-width: 60%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .badge { padding: 0.2rem 0.6rem; border-radius: 1rem; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; }
    .badge-success { background: rgba(34, 197, 94, 0.2); color: #22c55e; }
    .badge-error { background: rgba(239, 68, 68, 0.2); color: #ef4444; }
    .badge-warning { background: rgba(234, 179, 8, 0.2); color: #eab308; }
    .badge-info { background: rgba(59, 130, 246, 0.2); color: #3b82f6; }
    .error-section { border-color: #7f1d1d; }
    .error-section .section-header { background: rgba(127, 29, 29, 0.3); }
    .error-item { font-family: monospace; font-size: 0.75rem; color: #fca5a5; padding: 0.5rem 1.25rem; border-bottom: 1px solid #2a1a1a; }
    .footer { text-align: center; color: #666; font-size: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #222; }
    .duration { color: #888; font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🔍 Reality Mode Report</h1>
    <p class="subtitle">guardrail • ${new Date().toLocaleString()} • <span class="duration">${(results.duration / 1000).toFixed(1)}s</span></p>
    
    <div class="score-card">
      <div class="score">${score}</div>
      <div class="grade">Grade: ${grade}</div>
      <p class="verdict">${verdict}</p>
    </div>
    
    <div class="metrics">
      <div class="metric">
        <div class="metric-value">${results.coverage.routes}/${results.routes.length}</div>
        <div class="metric-label">Routes Working</div>
      </div>
      <div class="metric">
        <div class="metric-value">${results.coverage.elements}/${results.elements.length}</div>
        <div class="metric-label">Elements Working</div>
      </div>
      <div class="metric">
        <div class="metric-value">${results.coverage.forms}/${results.forms.length}</div>
        <div class="metric-label">Forms Working</div>
      </div>
      <div class="metric">
        <div class="metric-value">${results.errors.length}</div>
        <div class="metric-label">Errors Captured</div>
      </div>
      <div class="metric">
        <div class="metric-value">${results.networkCalls.length}</div>
        <div class="metric-label">API Calls</div>
      </div>
    </div>
    
    <div class="section">
      <div class="section-header">🗺️ Routes (${results.routes.length})</div>
      <div class="section-content">
        ${results.routes.map(r => `
          <div class="item">
            <span class="item-name">${r.path}</span>
            <span class="badge badge-${r.status === 'success' ? 'success' : 'error'}">${r.status}${r.responseTime ? ` • ${r.responseTime}ms` : ''}</span>
          </div>
        `).join('')}
      </div>
    </div>
    
    <div class="section">
      <div class="section-header">🔘 Interactive Elements (${results.elements.length})</div>
      <div class="section-content">
        ${results.elements.slice(0, 30).map(e => `
          <div class="item">
            <span class="item-name">${e.text || e.selector}</span>
            <span class="badge badge-${e.status === 'success' ? 'success' : e.status === 'no-change' ? 'warning' : e.status === 'hidden' ? 'info' : 'error'}">${e.status}</span>
          </div>
        `).join('')}
        ${results.elements.length > 30 ? `<div class="item"><span class="item-name" style="color:#888">+ ${results.elements.length - 30} more...</span></div>` : ''}
      </div>
    </div>
    
    <div class="section">
      <div class="section-header">📝 Forms (${results.forms.length})</div>
      <div class="section-content">
        ${results.forms.map(f => `
          <div class="item">
            <span class="item-name">${f.selector}</span>
            <span class="badge badge-${f.status === 'success' ? 'success' : 'error'}">${f.status} • ${f.fieldsFilledCount} fields</span>
          </div>
        `).join('')}
      </div>
    </div>
    
    ${results.errors.length > 0 ? `
    <div class="section error-section">
      <div class="section-header">❌ Errors (${results.errors.length})</div>
      <div class="section-content">
        ${results.errors.slice(0, 15).map(e => `
          <div class="error-item">[${e.type}] ${e.message}</div>
        `).join('')}
      </div>
    </div>
    ` : ''}
    
    <div class="section">
      <div class="section-header">📡 API Calls (${results.networkCalls.length})</div>
      <div class="section-content">
        ${results.networkCalls.slice(0, 20).map(n => `
          <div class="item">
            <span class="item-name">${n.method} ${n.url}</span>
            <span class="badge badge-${n.status < 400 ? 'success' : 'error'}">${n.status}</span>
          </div>
        `).join('')}
      </div>
    </div>
    
    <div class="footer">
      Generated by guardrail Reality Mode • <a href="https://guardrailai.dev" style="color:#3b82f6">guardrailai.dev</a>
    </div>
  </div>
</body>
</html>`;
}
