/**
 * Git Hooks Installer
 * Installs and configures husky or lefthook for pre-commit/pre-push hooks
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import type { GuardrailConfig } from './templates';

export type HookRunner = 'husky' | 'lefthook';

export interface HooksInstallerOptions {
  projectPath: string;
  config: GuardrailConfig;
  runner?: HookRunner;
  preCommit?: boolean;
  prePush?: boolean;
}

export interface HooksInstallerResult {
  success: boolean;
  runner: HookRunner;
  installedHooks: string[];
  error?: string;
}

function detectExistingHookRunner(projectPath: string): HookRunner | null {
  if (existsSync(join(projectPath, '.husky'))) {
    return 'husky';
  }
  if (existsSync(join(projectPath, 'lefthook.yml')) || existsSync(join(projectPath, '.lefthook.yml'))) {
    return 'lefthook';
  }
  return null;
}

function detectPackageManager(projectPath: string): 'npm' | 'yarn' | 'pnpm' {
  if (existsSync(join(projectPath, 'pnpm-lock.yaml'))) {
    return 'pnpm';
  }
  if (existsSync(join(projectPath, 'yarn.lock'))) {
    return 'yarn';
  }
  return 'npm';
}

function generatePreCommitScript(_config: GuardrailConfig): string {
  // guardrail pre-commit scans ONLY staged files — secrets, mock data, auth issues
  // Typically completes in <2 seconds
  return `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

guardrail pre-commit
`;
}

function generatePrePushScript(config: GuardrailConfig): string {
  const commands: string[] = [];

  if (config.scans.secrets.enabled) {
    commands.push('guardrail scan:secrets --path . --exit-code');
  }

  if (config.scans.vulnerabilities.enabled) {
    const threshold = config.scans.vulnerabilities.threshold || 'high';
    commands.push(`guardrail scan:vulnerabilities --path . --threshold ${threshold} --exit-code`);
  }

  commands.push('guardrail ship --path . --exit-code');

  return `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🛡️  Running guardrail pre-push checks..."

${commands.join('\n\n')}

echo "✅ guardrail pre-push checks passed!"
`;
}

function generateLefthookConfig(config: GuardrailConfig, options: HooksInstallerOptions): string {
  const hooks: Record<string, any> = {};

  if (options.preCommit !== false) {
    hooks['pre-commit'] = {
      parallel: true,
      commands: {
        'guardrail-secrets': {
          run: `guardrail scan:secrets --path . --threshold ${config.scans.secrets.threshold || 'high'} --exit-code`,
          stage_fixed: true,
        },
      },
    };
  }

  if (options.prePush !== false) {
    const prePushCommands: Record<string, any> = {};

    if (config.scans.secrets.enabled) {
      prePushCommands['guardrail-secrets'] = {
        run: 'guardrail scan:secrets --path . --exit-code',
      };
    }

    if (config.scans.vulnerabilities.enabled) {
      prePushCommands['guardrail-vulns'] = {
        run: `guardrail scan:vulnerabilities --path . --threshold ${config.scans.vulnerabilities.threshold || 'high'} --exit-code`,
      };
    }

    prePushCommands['guardrail-ship'] = {
      run: 'guardrail ship --path . --exit-code',
    };

    hooks['pre-push'] = {
      parallel: false,
      commands: prePushCommands,
    };
  }

  return `# guardrail Git Hooks Configuration
# Generated by guardrail init
# Learn more: https://github.com/evilmartians/lefthook

${Object.entries(hooks).map(([hookName, hookConfig]) => {
  const commands = hookConfig.commands;
  const commandsYaml = Object.entries(commands).map(([cmdName, cmdConfig]: [string, any]) => {
    let yaml = `    ${cmdName}:\n      run: ${cmdConfig.run}`;
    if (cmdConfig.stage_fixed) {
      yaml += `\n      stage_fixed: true`;
    }
    return yaml;
  }).join('\n');

  return `${hookName}:
  parallel: ${hookConfig.parallel}
  commands:
${commandsYaml}`;
}).join('\n\n')}
`;
}

function installHusky(projectPath: string, packageManager: 'npm' | 'yarn' | 'pnpm'): boolean {
  try {
    const installCmd = packageManager === 'npm' 
      ? 'npm install --save-dev husky'
      : packageManager === 'yarn'
        ? 'yarn add --dev husky'
        : 'pnpm add --save-dev husky';

    execSync(installCmd, { cwd: projectPath, stdio: 'pipe' });

    const initCmd = 'npx husky init';
    execSync(initCmd, { cwd: projectPath, stdio: 'pipe' });

    return true;
  } catch {
    return false;
  }
}

function installLefthook(projectPath: string, packageManager: 'npm' | 'yarn' | 'pnpm'): boolean {
  try {
    const installCmd = packageManager === 'npm'
      ? 'npm install --save-dev lefthook'
      : packageManager === 'yarn'
        ? 'yarn add --dev lefthook'
        : 'pnpm add --save-dev lefthook';

    execSync(installCmd, { cwd: projectPath, stdio: 'pipe' });

    execSync('npx lefthook install', { cwd: projectPath, stdio: 'pipe' });

    return true;
  } catch {
    return false;
  }
}

function updatePackageJsonScripts(projectPath: string, runner: HookRunner): void {
  const packageJsonPath = join(projectPath, 'package.json');
  if (!existsSync(packageJsonPath)) return;

  try {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    
    if (!packageJson.scripts) {
      packageJson.scripts = {};
    }

    if (runner === 'husky') {
      packageJson.scripts['prepare'] = 'husky';
    } else {
      packageJson.scripts['prepare'] = 'lefthook install';
    }

    writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n', 'utf-8');
  } catch {
    // Failed to update package.json, continue anyway
  }
}

export function installHooks(options: HooksInstallerOptions): HooksInstallerResult {
  const { projectPath, config, preCommit = true, prePush = true } = options;
  const installedHooks: string[] = [];

  const existingRunner = detectExistingHookRunner(projectPath);
  const runner = options.runner || existingRunner || 'husky';
  const packageManager = detectPackageManager(projectPath);

  if (runner === 'husky') {
    const huskyDir = join(projectPath, '.husky');
    const huskyExists = existsSync(huskyDir);

    if (!huskyExists) {
      const installed = installHusky(projectPath, packageManager);
      if (!installed) {
        if (!existsSync(huskyDir)) {
          mkdirSync(huskyDir, { recursive: true });
        }
        const huskyShDir = join(huskyDir, '_');
        if (!existsSync(huskyShDir)) {
          mkdirSync(huskyShDir, { recursive: true });
        }
        writeFileSync(
          join(huskyShDir, 'husky.sh'),
          `#!/usr/bin/env sh
if [ -z "$husky_skip_init" ]; then
  debug () {
    if [ "$HUSKY_DEBUG" = "1" ]; then
      echo "husky (debug) - $1"
    fi
  }

  readonly hook_name="$(basename -- "$0")"
  debug "starting $hook_name..."

  if [ "$HUSKY" = "0" ]; then
    debug "HUSKY env variable is set to 0, skipping hook"
    exit 0
  fi

  if [ -f ~/.huskyrc ]; then
    debug "sourcing ~/.huskyrc"
    . ~/.huskyrc
  fi

  readonly husky_skip_init=1
  export husky_skip_init
  sh -e "$0" "$@"
  exitCode="$?"

  if [ $exitCode != 0 ]; then
    echo "husky - $hook_name hook exited with code $exitCode (error)"
  fi

  if [ $exitCode = 127 ]; then
    echo "husky - command not found in PATH=$PATH"
  fi

  exit $exitCode
fi
`,
          'utf-8'
        );
        try {
          chmodSync(join(huskyShDir, 'husky.sh'), 0o755);
        } catch (error) {
          // Failed to install hook - continue with other hooks
        }
      }
    }

    if (preCommit) {
      const preCommitPath = join(huskyDir, 'pre-commit');
      writeFileSync(preCommitPath, generatePreCommitScript(config), 'utf-8');
      try {
        chmodSync(preCommitPath, 0o755);
      } catch (error) {
        // Failed to set permissions - file will still work
      }
      installedHooks.push('pre-commit');
    }

    if (prePush) {
      const prePushPath = join(huskyDir, 'pre-push');
      writeFileSync(prePushPath, generatePrePushScript(config), 'utf-8');
      try {
        chmodSync(prePushPath, 0o755);
      } catch (error) {
        // Failed to set permissions - file will still work
      }
      installedHooks.push('pre-push');
    }

    updatePackageJsonScripts(projectPath, 'husky');

  } else {
    if (!existingRunner) {
      const installed = installLefthook(projectPath, packageManager);
      if (!installed) {
        // Manual fallback - just create config file
      }
    }

    const lefthookConfig = generateLefthookConfig(config, { ...options, preCommit, prePush });
    writeFileSync(join(projectPath, 'lefthook.yml'), lefthookConfig, 'utf-8');

    if (preCommit) installedHooks.push('pre-commit');
    if (prePush) installedHooks.push('pre-push');

    updatePackageJsonScripts(projectPath, 'lefthook');

    try {
      execSync('npx lefthook install', { cwd: projectPath, stdio: 'pipe' });
    } catch {
      // Lefthook install failed, hooks will need to be installed manually
    }
  }

  return {
    success: true,
    runner,
    installedHooks,
  };
}

export function getRecommendedRunner(projectPath: string): HookRunner {
  const existing = detectExistingHookRunner(projectPath);
  if (existing) return existing;

  const packageJsonPath = join(projectPath, 'package.json');
  if (existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
      if (pkg.devDependencies?.husky || pkg.dependencies?.husky) {
        return 'husky';
      }
      if (pkg.devDependencies?.lefthook || pkg.dependencies?.lefthook) {
        return 'lefthook';
      }
    } catch (error) {
      // Failed to read package.json - using default runner
    }
  }

  return 'husky';
}
