/**
 * Environment Validation
 * Auto-generated by guardrail
 * Run this at application startup to validate environment
 */

export interface Env {
  NODE_ENV: string;
  PORT?: number;
  LOG_LEVEL?: string;
  DATABASE_URL: string;
  DATABASE_POOL_SIZE?: number;
  API_URL?: string;
  CORS_ORIGIN?: string;
  RATE_LIMIT_MAX?: number;
  RATE_LIMIT_WINDOW_MS?: number;
  OPENAI_API_KEY?: string;
  ANTHROPIC_API_KEY?: string;
}

export function validateEnv(): Env {
  const errors: string[] = [];

  if (!process.env.NODE_ENV) {
    errors.push("Missing required environment variable: NODE_ENV");
  }
  if (!process.env.DATABASE_URL) {
    errors.push("Missing required environment variable: DATABASE_URL");
  }

  if (errors.length > 0) {
    console.error("Environment validation failed:");
    errors.forEach((e) => console.error("  -", e));
    process.exit(1);
  }

  return {
    NODE_ENV: process.env.NODE_ENV || "development",
    PORT: Number(process.env.PORT) || 3000,
    LOG_LEVEL: process.env.LOG_LEVEL || "info",
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_POOL_SIZE: Number(process.env.DATABASE_POOL_SIZE) || 10,
    API_URL: process.env.API_URL || undefined,
    CORS_ORIGIN: process.env.CORS_ORIGIN || undefined,
    RATE_LIMIT_MAX: Number(process.env.RATE_LIMIT_MAX) || 100,
    RATE_LIMIT_WINDOW_MS: Number(process.env.RATE_LIMIT_WINDOW_MS) || 60000,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY || undefined,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || undefined,
  } as Env;
}
