"use strict";
/**
 * Pre-commit Hooks Integration
 *
 * Generates pre-commit hook configurations for local validation
 * before commits are pushed to the repository
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.preCommitGenerator = exports.PreCommitGenerator = void 0;
class PreCommitGenerator {
    /**
     * Generate Husky pre-commit configuration
     */
    generateHuskyConfig(config) {
        const commands = [];
        if (config.runLint) {
            commands.push('npx lint-staged');
        }
        if (config.scanSecrets) {
            commands.push('npx Guardrail scan:secrets --staged --fail-on-detection');
        }
        if (config.validateTypes) {
            commands.push('npx tsc --noEmit');
        }
        return {
            hooks: {
                'pre-commit': commands.join(' && '),
                'pre-push': this.generatePrePushCommands(config),
                'commit-msg': 'npx commitlint --edit $1',
            },
        };
    }
    /**
     * Generate pre-push commands
     */
    generatePrePushCommands(config) {
        const commands = [];
        if (config.scanVulnerabilities) {
            commands.push('npx Guardrail scan:vulnerabilities');
        }
        if (config.checkCompliance) {
            commands.push('npx Guardrail scan:compliance');
        }
        if (config.runTests) {
            commands.push('npm test');
        }
        return commands.join(' && ');
    }
    /**
     * Generate .husky/pre-commit script
     */
    generatePreCommitScript(config) {
        const lines = [
            '#!/usr/bin/env sh',
            '. "$(dirname -- "$0")/_/husky.sh"',
            '',
            '# Guardrail Pre-commit Hook',
            '# Generated by Guardrail AI',
            '',
        ];
        if (config.runLint) {
            lines.push('echo "Running lint-staged..."');
            lines.push('npx lint-staged || exit 1');
            lines.push('');
        }
        if (config.scanSecrets) {
            lines.push('echo "Scanning for secrets..."');
            lines.push('npx Guardrail scan:secrets --staged --fail-on-detection || {');
            lines.push('  echo "ERROR: Secrets detected in staged files!"');
            lines.push('  echo "Please remove secrets before committing."');
            lines.push('  exit 1');
            lines.push('}');
            lines.push('');
        }
        if (config.validateTypes) {
            lines.push('echo "Checking TypeScript types..."');
            lines.push('npx tsc --noEmit || exit 1');
            lines.push('');
        }
        if (config.maxFileSize > 0) {
            lines.push(`echo "Checking file sizes (max ${config.maxFileSize}KB)..."`);
            lines.push(`MAX_SIZE=${config.maxFileSize * 1024}`);
            lines.push('for file in $(git diff --cached --name-only); do');
            lines.push('  if [ -f "$file" ]; then');
            lines.push('    size=$(wc -c < "$file")');
            lines.push('    if [ $size -gt $MAX_SIZE ]; then');
            lines.push('      echo "ERROR: $file exceeds maximum file size"');
            lines.push('      exit 1');
            lines.push('    fi');
            lines.push('  fi');
            lines.push('done');
            lines.push('');
        }
        lines.push('echo "Pre-commit checks passed!"');
        return lines.join('\n');
    }
    /**
     * Generate .husky/pre-push script
     */
    generatePrePushScript(config) {
        const lines = [
            '#!/usr/bin/env sh',
            '. "$(dirname -- "$0")/_/husky.sh"',
            '',
            '# Guardrail Pre-push Hook',
            '# Generated by Guardrail AI',
            '',
        ];
        if (config.scanVulnerabilities) {
            lines.push('echo "Scanning for vulnerabilities..."');
            const failCondition = config.blockOnCritical
                ? (config.blockOnHigh ? '--fail-on-high' : '--fail-on-critical')
                : '';
            lines.push(`npx Guardrail scan:vulnerabilities ${failCondition} || {`);
            lines.push('  echo "ERROR: Vulnerabilities detected!"');
            lines.push('  exit 1');
            lines.push('}');
            lines.push('');
        }
        if (config.checkCompliance) {
            lines.push('echo "Checking compliance..."');
            lines.push('npx Guardrail scan:compliance || {');
            lines.push('  echo "WARNING: Compliance issues detected"');
            lines.push('}');
            lines.push('');
        }
        if (config.runTests) {
            lines.push('echo "Running tests..."');
            lines.push('npm test || {');
            lines.push('  echo "ERROR: Tests failed!"');
            lines.push('  exit 1');
            lines.push('}');
            lines.push('');
        }
        lines.push('echo "Pre-push checks passed!"');
        return lines.join('\n');
    }
    /**
     * Generate lint-staged configuration
     */
    generateLintStagedConfig(config) {
        const lintStaged = {};
        // TypeScript/JavaScript files
        lintStaged['*.{ts,tsx,js,jsx}'] = [
            'eslint --fix',
            'prettier --write',
        ];
        if (config.scanSecrets) {
            lintStaged['*.{ts,tsx,js,jsx}'].push('Guardrail scan:secrets --file');
        }
        // JSON files
        lintStaged['*.json'] = ['prettier --write'];
        // Markdown files
        lintStaged['*.md'] = ['prettier --write'];
        // CSS/SCSS files
        lintStaged['*.{css,scss}'] = ['prettier --write'];
        return lintStaged;
    }
    /**
     * Generate package.json scripts for hooks
     */
    generatePackageJsonScripts() {
        return {
            'prepare': 'husky install',
            'pre-commit': 'lint-staged',
            'Guardrail:secrets': 'Guardrail scan:secrets',
            'Guardrail:vulnerabilities': 'Guardrail scan:vulnerabilities',
            'Guardrail:compliance': 'Guardrail scan:compliance',
            'Guardrail:full': 'Guardrail scan:all',
        };
    }
    /**
     * Generate commitlint configuration
     */
    generateCommitlintConfig() {
        return {
            extends: ['@commitlint/config-conventional'],
            rules: {
                'type-enum': [
                    2,
                    'always',
                    [
                        'feat',
                        'fix',
                        'docs',
                        'style',
                        'refactor',
                        'perf',
                        'test',
                        'build',
                        'ci',
                        'chore',
                        'revert',
                        'security',
                    ],
                ],
                'subject-case': [2, 'always', 'lower-case'],
                'subject-max-length': [2, 'always', 72],
                'body-max-line-length': [2, 'always', 100],
            },
        };
    }
    /**
     * Generate default configuration
     */
    generateDefaultConfig() {
        return {
            scanSecrets: true,
            scanVulnerabilities: true,
            checkCompliance: false,
            validateTypes: true,
            runLint: true,
            runTests: false,
            blockOnCritical: true,
            blockOnHigh: false,
            maxFileSize: 500, // 500KB
            excludePatterns: [
                'node_modules/**',
                'dist/**',
                'build/**',
                '*.min.js',
                '*.bundle.js',
            ],
        };
    }
    /**
     * Generate setup instructions
     */
    generateSetupInstructions() {
        return `
# Guardrail Pre-commit Hooks Setup

## Installation

1. Install dependencies:
\`\`\`bash
npm install -D husky lint-staged @commitlint/cli @commitlint/config-conventional
\`\`\`

2. Initialize Husky:
\`\`\`bash
npx husky install
\`\`\`

3. Add prepare script to package.json:
\`\`\`json
{
  "scripts": {
    "prepare": "husky install"
  }
}
\`\`\`

4. Create pre-commit hook:
\`\`\`bash
npx husky add .husky/pre-commit "npx lint-staged"
\`\`\`

5. Create pre-push hook:
\`\`\`bash
npx husky add .husky/pre-push "npx Guardrail scan:vulnerabilities"
\`\`\`

## Configuration

Add lint-staged config to package.json:
\`\`\`json
{
  "lint-staged": {
    "*.{ts,tsx,js,jsx}": ["eslint --fix", "prettier --write"]
  }
}
\`\`\`

## Usage

Hooks will run automatically on:
- **Pre-commit**: Lint, format, and secret scanning
- **Pre-push**: Vulnerability and compliance scanning
- **Commit-msg**: Conventional commit validation
`.trim();
    }
}
exports.PreCommitGenerator = PreCommitGenerator;
// Export singleton
exports.preCommitGenerator = new PreCommitGenerator();
