/**
 * Codex / ChatGPT Instructions Generator
 * Generates .codex-instructions.md for OpenAI tools
 */

/**
 * Generate OpenAI Codex / ChatGPT instructions
 */
function generateCodexConfig(analysis, projectPath) {
  const p = analysis.patterns || {};
  const m = analysis.monorepo || {};
  
  return `# OpenAI Codex / ChatGPT Project Instructions

## Project: ${analysis.name}

### Overview

- **Framework:** ${analysis.framework || "Unknown"}
- **Language:** ${analysis.language || "JavaScript"}
- **Architecture:** ${analysis.architecture}
${m.isMonorepo ? `- **Monorepo:** ${m.type} with ${m.workspaces?.length || 0} workspaces` : ""}

### Tech Stack

${analysis.hasNextjs ? "- Next.js" : ""}
${analysis.hasReact ? "- React" : ""}
${analysis.hasTypescript ? "- TypeScript (strict mode)" : ""}
${analysis.hasPrisma ? "- Prisma ORM" : ""}
${analysis.hasTailwind ? "- Tailwind CSS" : ""}
${p.stateManagement ? `- State: ${p.stateManagement}` : ""}
${p.validation ? `- Validation: ${p.validation}` : ""}
${p.authentication ? `- Auth: ${p.authentication}` : ""}
${p.dataFetching?.length ? `- Data Fetching: ${p.dataFetching.join(", ")}` : ""}
${p.testing?.length ? `- Testing: ${p.testing.join(", ")}` : ""}

### Key Directories

${analysis.directories.map(d => `- \`${d}/\``).join("\n")}

${m.isMonorepo && m.workspaces?.length > 0 ? `### Workspaces

${m.workspaces.slice(0, 10).map(w => `- \`${w.path}\` - ${w.name}`).join("\n")}
` : ""}

### Components (${analysis.components?.length || 0})

${analysis.components?.slice(0, 20).map(c => `- ${c}`).join("\n") || "None detected"}

### Data Models (${analysis.models?.length || 0})

${analysis.models?.slice(0, 15).map(m => `- ${m}`).join("\n") || "None detected"}

### Custom Hooks

${p.hooks?.slice(0, 10).map(h => `- ${h}`).join("\n") || "None detected"}

### API Routes

${analysis.apiRoutes?.slice(0, 15).map(r => `- ${r}`).join("\n") || "None detected"}

### Environment Variables

${analysis.envVars?.variables?.slice(0, 15).map(v => `- ${v}`).join("\n") || "Check .env.example"}

### NPM Scripts

${analysis.scripts?.slice(0, 8).map(s => `- \`npm run ${s.name}\` - ${s.command}`).join("\n") || "See package.json"}

### Coding Rules

1. Follow existing patterns in the codebase
2. Use TypeScript with strict types - no \`any\`
3. Use existing components before creating new ones
4. Use existing hooks before creating new ones
5. Validate all API inputs with ${p.validation || "zod"}
6. Use path aliases (@/) for imports
7. Follow the established file naming conventions
${analysis.hasTailwind ? "8. Use Tailwind CSS for styling" : ""}

### Anti-Patterns to Avoid

${p.antiPatterns?.map(ap => `- ❌ ${ap.message}`).join("\n") || "- No console.log in production\n- No hardcoded secrets\n- No mock data in production"}

### File Naming Conventions

- Components: ${analysis.conventions?.naming?.components || "PascalCase"} (e.g., \`Button.tsx\`)
- Utilities: camelCase (e.g., \`formatDate.ts\`)
- Types: \`.types.ts\` or \`.d.ts\`

### Import Order

1. React/framework imports
2. Third-party libraries
3. Internal components (\`@/components/\`)
4. Internal utilities (\`@/lib/\`)
5. Types
6. Styles

---

*Generated by guardrail AI - https://guardrailai.dev*
`;
}

module.exports = {
  generateCodexConfig,
};
