/**
 * Context Injection Generator
 *
 * Generates .guardrail/context.md — a human-readable AND AI-consumable
 * file containing verified project truth. Any AI tool (Claude, Cursor,
 * Copilot, ChatGPT) can read this file to prevent hallucinations.
 *
 * This is the file-based complement to the MCP resource-based injection.
 */

const fs = require("fs");
const path = require("path");

/**
 * Generate the context.md injection file
 *
 * @param {object} analysis - Project analysis from analyzeProject()
 * @param {string} projectPath - Absolute path to project root
 * @param {object} options - Generation options
 * @returns {string} Markdown content
 */
function generateContextMd(analysis, projectPath, options = {}) {
  const p = analysis.patterns || {};
  const t = analysis.types || {};
  const env = analysis.envVars || {};
  const mono = analysis.monorepo || {};
  const lines = [];

  // Header
  lines.push("# Guardrail Context Injection");
  lines.push("");
  lines.push("> **This file is auto-generated by `guardrail context --inject`.**");
  lines.push("> **It contains VERIFIED project truth. AI tools should treat this as ground truth.**");
  lines.push("> **Do NOT edit manually — regenerate with `guardrail context --inject`.**");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  // Project identity
  lines.push("## Project");
  lines.push("");
  lines.push(`- **Name:** ${analysis.name || "unknown"}`);
  lines.push(`- **Framework:** ${analysis.framework || "unknown"}`);
  lines.push(`- **Language:** ${analysis.language || "unknown"}`);
  lines.push(`- **Architecture:** ${analysis.architecture || "unknown"}`);
  if (analysis.stats) {
    lines.push(`- **Size:** ${analysis.stats.totalFiles || 0} files, ~${Math.round((analysis.stats.totalLines || 0) / 1000)}k lines`);
  }
  if (mono.isMonorepo) {
    lines.push(`- **Monorepo:** ${mono.type} (${mono.workspaces?.length || 0} workspaces)`);
  }
  lines.push("");

  // Tech stack
  lines.push("## Tech Stack");
  lines.push("");
  const stack = [];
  if (analysis.hasNextjs) stack.push("Next.js");
  if (analysis.hasReact) stack.push("React");
  if (analysis.hasTypescript) stack.push("TypeScript");
  if (analysis.hasPrisma) stack.push("Prisma");
  if (analysis.hasTailwind) stack.push("Tailwind CSS");
  if (p.stateManagement) stack.push(`State: ${p.stateManagement}`);
  if (p.validation) stack.push(`Validation: ${p.validation}`);
  if (p.authentication) stack.push(`Auth: ${p.authentication}`);
  lines.push(stack.join(" | ") || "Not detected");
  lines.push("");

  // API Routes
  if (analysis.apiRoutes?.length > 0) {
    lines.push("## Verified API Routes");
    lines.push("");
    lines.push("**Use ONLY these routes. Do NOT invent new ones.**");
    lines.push("");
    lines.push("| Method | Path | File |");
    lines.push("|--------|------|------|");
    for (const route of analysis.apiRoutes) {
      const method = route.method || "GET";
      const routePath = route.path || route.route || route;
      const file = route.file || "";
      lines.push(`| ${method} | \`${routePath}\` | ${file} |`);
    }
    lines.push("");
  }

  // Types and interfaces
  if (t.interfaces?.length > 0 || t.types?.length > 0) {
    lines.push("## Types & Interfaces");
    lines.push("");
    lines.push("**Use these exact type names. Do NOT create duplicates.**");
    lines.push("");
    const allTypes = [...(t.interfaces || []), ...(t.types || [])];
    for (const type of allTypes.slice(0, 50)) {
      lines.push(`- \`${type.name}\` — ${type.file}:${type.line}`);
    }
    if (allTypes.length > 50) {
      lines.push(`- _...and ${allTypes.length - 50} more_`);
    }
    lines.push("");
  }

  // Environment variables
  if (env.variables?.length > 0) {
    lines.push("## Environment Variables");
    lines.push("");
    lines.push("**Use ONLY these env var names. Do NOT invent new ones.**");
    lines.push("");
    for (const v of env.variables) {
      const name = typeof v === "string" ? v : v.name;
      lines.push(`- \`${name}\``);
    }
    lines.push("");
  }

  // Components
  if (analysis.components?.length > 0) {
    lines.push("## Components");
    lines.push("");
    lines.push("**Import from these before creating new components.**");
    lines.push("");
    for (const comp of analysis.components.slice(0, 30)) {
      const name = typeof comp === "string" ? comp : comp.name;
      const file = typeof comp === "string" ? "" : ` (${comp.file})`;
      lines.push(`- \`${name}\`${file}`);
    }
    if (analysis.components.length > 30) {
      lines.push(`- _...and ${analysis.components.length - 30} more_`);
    }
    lines.push("");
  }

  // Patterns (golden)
  if (p.hooks?.length > 0) {
    lines.push("## Custom Hooks (Reuse These)");
    lines.push("");
    for (const hook of p.hooks) {
      lines.push(`- \`${hook}\``);
    }
    lines.push("");
  }

  if (p.dataFetching?.length > 0) {
    lines.push("## Data Fetching Patterns");
    lines.push("");
    for (const df of p.dataFetching) {
      lines.push(`- ${df}`);
    }
    lines.push("");
  }

  // Anti-patterns
  if (p.antiPatterns?.length > 0) {
    lines.push("## ⚠️ Anti-Patterns to AVOID");
    lines.push("");
    const seen = new Set();
    for (const ap of p.antiPatterns) {
      const key = ap.message || ap.name;
      if (seen.has(key)) continue;
      seen.add(key);
      const icon = ap.severity === "error" ? "🔴" : ap.severity === "warning" ? "🟡" : "🔵";
      lines.push(`- ${icon} ${key}`);
    }
    lines.push("");
  }

  // Violation history (learning loop)
  const historyPath = path.join(projectPath, ".guardrail", "violation-history.json");
  if (fs.existsSync(historyPath)) {
    try {
      const history = JSON.parse(fs.readFileSync(historyPath, "utf-8"));
      const repeats = (history.patterns || []).filter((p) => p.count >= 3);
      if (repeats.length > 0) {
        lines.push("## 🔴 Repeat Violations (CRITICAL)");
        lines.push("");
        lines.push("These issues keep recurring. The AI MUST avoid generating code with these patterns:");
        lines.push("");
        for (const v of repeats) {
          lines.push(`- **${v.type}** in \`${v.file}\` — ${v.count}x occurrences`);
          if (v.wasFixedThenReintroduced) {
            lines.push(`  - ⚡ Was FIXED then RE-INTRODUCED`);
          }
        }
        lines.push("");
      }
    } catch {
      // Ignore parse errors
    }
  }

  // Directory structure
  if (analysis.directories?.length > 0) {
    lines.push("## Directory Structure");
    lines.push("");
    for (const dir of analysis.directories.slice(0, 20)) {
      const name = typeof dir === "string" ? dir : dir.name;
      lines.push(`- \`${name}/\``);
    }
    lines.push("");
  }

  // Rules
  lines.push("## Rules");
  lines.push("");
  lines.push("1. Never hardcode secrets — use environment variables");
  lines.push("2. No mock data in production code");
  lines.push("3. No `any` types — use proper TypeScript types from the schema above");
  lines.push("4. Follow existing patterns in the codebase");
  lines.push("5. Use existing components/hooks before creating new ones");
  lines.push("6. API routes must validate all input");
  lines.push("7. Import from existing modules — check the types list above");
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("*Generated by [Guardrail](https://guardrail.dev) — Ship Real Code. Prove It.*");

  return lines.join("\n");
}

/**
 * Generate enriched context.md using truthpack data if available
 */
function generateContextMdFromTruthpack(projectPath) {
  const truthpackDir = path.join(projectPath, ".guardrail-context");

  if (!fs.existsSync(path.join(truthpackDir, "truthpack.json"))) {
    return null;
  }

  const lines = [];
  const readJson = (file) => {
    try {
      return JSON.parse(fs.readFileSync(path.join(truthpackDir, file), "utf-8"));
    } catch {
      return null;
    }
  };

  const truthpack = readJson("truthpack.json");
  const routes = readJson("routes.json");
  const symbols = readJson("symbols.json");
  const patterns = readJson("patterns.json");
  const antipatterns = readJson("antipatterns.json");
  const deps = readJson("deps.json");
  const risk = readJson("risk.json");

  lines.push("# Guardrail Context Injection (Truthpack)");
  lines.push("");
  lines.push("> **VERIFIED project truth from static analysis. Treat as ground truth.**");
  lines.push("");
  lines.push(`Generated: ${truthpack?.generatedAt || new Date().toISOString()}`);
  lines.push("");

  // Stack
  if (truthpack?.stack) {
    lines.push("## Stack");
    lines.push("");
    lines.push(`- **Framework:** ${truthpack.stack.framework}`);
    lines.push(`- **Language:** ${truthpack.stack.language}`);
    lines.push(`- **Package Manager:** ${truthpack.stack.packageManager}`);
    if (truthpack.stack.runtime) lines.push(`- **Runtime:** ${truthpack.stack.runtime}`);
    lines.push("");
  }

  // Routes
  if (routes?.length > 0) {
    lines.push("## Verified API Routes");
    lines.push("");
    lines.push("| Method | Path | Auth | Handler | File |");
    lines.push("|--------|------|------|---------|------|");
    for (const r of routes) {
      lines.push(`| ${r.method} | \`${r.path}\` | ${r.auth ? "✅" : "❌"} | ${r.handler} | ${r.file}:${r.line} |`);
    }
    lines.push("");
  }

  // Symbols (top exported)
  if (symbols?.length > 0) {
    lines.push("## Key Exported Symbols");
    lines.push("");
    const byType = {};
    for (const s of symbols) {
      if (!byType[s.type]) byType[s.type] = [];
      byType[s.type].push(s);
    }
    for (const [type, syms] of Object.entries(byType)) {
      lines.push(`### ${type}s`);
      lines.push("");
      for (const s of syms.slice(0, 20)) {
        lines.push(`- \`${s.name}\` — ${s.file}:${s.line}`);
      }
      lines.push("");
    }
  }

  // Risk hotspots
  if (risk?.length > 0) {
    const critical = risk.filter((r) => r.severity === "critical" || r.severity === "high");
    if (critical.length > 0) {
      lines.push("## ⚠️ Risk Hotspots");
      lines.push("");
      for (const r of critical.slice(0, 15)) {
        lines.push(`- **${r.category}** (${r.severity}) — ${r.file}:${r.line}: ${r.description}`);
      }
      lines.push("");
    }
  }

  // Patterns
  if (patterns?.length > 0) {
    const golden = patterns.filter((p) => p.type === "golden");
    if (golden.length > 0) {
      lines.push("## Golden Patterns (Follow These)");
      lines.push("");
      for (const p of golden.slice(0, 10)) {
        lines.push(`- **${p.name}** — ${p.description} (${p.file})`);
      }
      lines.push("");
    }
  }

  if (antipatterns?.length > 0) {
    const unique = new Map();
    for (const a of antipatterns) {
      if (!unique.has(a.name)) unique.set(a.name, a);
    }
    lines.push("## Anti-Patterns to AVOID");
    lines.push("");
    for (const [, a] of [...unique].slice(0, 15)) {
      lines.push(`- **${a.name}** — ${a.description}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [Guardrail](https://guardrail.dev) — Ship Real Code. Prove It.*");

  return lines.join("\n");
}

module.exports = {
  generateContextMd,
  generateContextMdFromTruthpack,
};
