import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test", "staging"]>>;
    PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    HOST: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    JWT_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodOptional<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    GITHUB_CLIENT_ID: z.ZodOptional<z.ZodString>;
    GITHUB_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    GITHUB_CALLBACK_URL: z.ZodOptional<z.ZodString>;
    GITHUB_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    STRIPE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    STRIPE_PUBLISHABLE_KEY: z.ZodOptional<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    STRIPE_PRICE_ID_STARTER: z.ZodOptional<z.ZodString>;
    STRIPE_PRICE_ID_PRO: z.ZodOptional<z.ZodString>;
    STRIPE_PRICE_ID_ENTERPRISE: z.ZodOptional<z.ZodString>;
    API_BASE_URL: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_API_URL: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_APP_URL: z.ZodOptional<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    RATE_LIMIT_MAX_REQUESTS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    SENTRY_ORG: z.ZodOptional<z.ZodString>;
    SENTRY_PROJECT: z.ZodOptional<z.ZodString>;
    ENABLE_METRICS: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    ENABLE_AI_FEATURES: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    Guardrail_DEMO_MODE: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    Guardrail_POLICY_STRICT: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "test" | "development" | "production" | "staging";
    DATABASE_URL: string;
    PORT: number;
    HOST: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    CORS_ORIGIN: string;
    RATE_LIMIT_WINDOW_MS: number;
    RATE_LIMIT_MAX_REQUESTS: number;
    ENABLE_METRICS: boolean;
    ENABLE_AI_FEATURES: boolean;
    Guardrail_DEMO_MODE: boolean;
    Guardrail_POLICY_STRICT: boolean;
    JWT_REFRESH_SECRET?: string | undefined;
    GITHUB_CLIENT_ID?: string | undefined;
    GITHUB_CLIENT_SECRET?: string | undefined;
    GITHUB_CALLBACK_URL?: string | undefined;
    GITHUB_WEBHOOK_SECRET?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_PRICE_ID_STARTER?: string | undefined;
    STRIPE_PRICE_ID_PRO?: string | undefined;
    STRIPE_PRICE_ID_ENTERPRISE?: string | undefined;
    API_BASE_URL?: string | undefined;
    NEXT_PUBLIC_API_URL?: string | undefined;
    NEXT_PUBLIC_APP_URL?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    REDIS_URL?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ORG?: string | undefined;
    SENTRY_PROJECT?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    NODE_ENV?: "test" | "development" | "production" | "staging" | undefined;
    PORT?: string | undefined;
    HOST?: string | undefined;
    JWT_REFRESH_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    GITHUB_CLIENT_ID?: string | undefined;
    GITHUB_CLIENT_SECRET?: string | undefined;
    GITHUB_CALLBACK_URL?: string | undefined;
    GITHUB_WEBHOOK_SECRET?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_PRICE_ID_STARTER?: string | undefined;
    STRIPE_PRICE_ID_PRO?: string | undefined;
    STRIPE_PRICE_ID_ENTERPRISE?: string | undefined;
    API_BASE_URL?: string | undefined;
    NEXT_PUBLIC_API_URL?: string | undefined;
    NEXT_PUBLIC_APP_URL?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    REDIS_URL?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    RATE_LIMIT_WINDOW_MS?: string | undefined;
    RATE_LIMIT_MAX_REQUESTS?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ORG?: string | undefined;
    SENTRY_PROJECT?: string | undefined;
    ENABLE_METRICS?: string | undefined;
    ENABLE_AI_FEATURES?: string | undefined;
    Guardrail_DEMO_MODE?: string | undefined;
    Guardrail_POLICY_STRICT?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function validateEnv(): Env;
export declare function getEnv(): Env;
export declare function checkRequiredEnv(): void;
export declare function isDevelopment(): boolean;
export declare function isProduction(): boolean;
export declare function isTest(): boolean;
export {};
//# sourceMappingURL=env.d.ts.map