/**
 * Reality Mode - Auto-generated Playwright Test
 * 
 * This test runs your app and intercepts all network calls to detect fake data.
 * Generated by guardrail Reality Mode.
 */

import { test, expect, Page, Request, Response } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const FAKE_DOMAIN_PATTERNS = [
  "localhost:\\d+",
  "127\\.0\\.0\\.1:\\d+",
  "jsonplaceholder\\.typicode\\.com",
  "reqres\\.in",
  "mockapi\\.io",
  "mocky\\.io",
  "httpbin\\.org",
  "\\.ngrok\\.io",
  "\\.ngrok-free\\.app",
  "staging\\.",
  "\\.local\\/",
  "\\.test\\/",
  "api\\.example\\.com",
  "fake\\.api",
  "demo\\.api"
];

const FAKE_RESPONSE_PATTERNS = [
  {
    "pattern": {},
    "name": "Demo invoice ID"
  },
  {
    "pattern": {},
    "name": "Demo user ID"
  },
  {
    "pattern": {},
    "name": "Demo customer ID"
  },
  {
    "pattern": {},
    "name": "Demo subscription ID"
  },
  {
    "pattern": {},
    "name": "Test Stripe key"
  },
  {
    "pattern": {},
    "name": "Test Stripe public key"
  },
  {
    "pattern": {},
    "name": "Demo success response"
  },
  {
    "pattern": {},
    "name": "Lorem ipsum placeholder"
  },
  {
    "pattern": {},
    "name": "Placeholder name"
  },
  {
    "pattern": {},
    "name": "Placeholder email"
  },
  {
    "pattern": {},
    "name": "Placeholder domain/image"
  },
  {
    "pattern": {},
    "name": "Fake ID pattern"
  },
  {
    "pattern": {},
    "name": "Simulated status"
  },
  {
    "pattern": {},
    "name": "Mock flag enabled"
  },
  {
    "pattern": {},
    "name": "Demo mode flag"
  }
];

interface Detection {
  type: 'fake-domain' | 'demo-data' | 'simulated-billing' | 'test-keys';
  url: string;
  evidence: string;
  timestamp: number;
}

interface ReplayStep {
  timestamp: number;
  type: 'request' | 'response' | 'action';
  data: any;
  detections: Detection[];
}

test.describe('Reality Mode Scan', () => {
  let detections: Detection[] = [];
  let replay: ReplayStep[] = [];
  
  test.beforeEach(async ({ page }) => {
    detections = [];
    replay = [];
    
    // Intercept all network requests
    page.on('request', (request: Request) => {
      const url = request.url();
      const step: ReplayStep = {
        timestamp: Date.now(),
        type: 'request',
        data: { url, method: request.method() },
        detections: []
      };
      
      // Check for fake domains
      for (const pattern of FAKE_DOMAIN_PATTERNS) {
        if (new RegExp(pattern, 'i').test(url)) {
          const detection: Detection = {
            type: 'fake-domain',
            url,
            evidence: `URL matches fake domain pattern: ${pattern}`,
            timestamp: Date.now()
          };
          step.detections.push(detection);
          detections.push(detection);
        }
      }
      
      replay.push(step);
    });
    
    page.on('response', async (response: Response) => {
      const url = response.url();
      let body = '';
      
      try {
        body = await response.text();
      } catch (e) {
        // Some responses can't be read
      }
      
      const step: ReplayStep = {
        timestamp: Date.now(),
        type: 'response',
        data: { url, status: response.status(), bodyPreview: body.slice(0, 500) },
        detections: []
      };
      
      // Check for demo data patterns
      for (const { pattern, name } of FAKE_RESPONSE_PATTERNS) {
        if (new RegExp(pattern.source || pattern, 'i').test(body)) {
          const detection: Detection = {
            type: 'demo-data',
            url,
            evidence: `Response contains ${name}`,
            timestamp: Date.now()
          };
          step.detections.push(detection);
          detections.push(detection);
        }
      }
      
      replay.push(step);
    });
  });
  
  test('should detect fake data in production flow', async ({ page }) => {
    // Navigate to the app
    await page.goto('http://localhost:3001');
    
    replay.push({
      timestamp: Date.now(),
      type: 'action',
      data: { type: 'navigation', url: 'http://localhost:3001' },
      detections: []
    });
    
    // Execute click paths
    const clickPaths = [
    [
        "[data-testid=\"login-button\"]",
        "[data-testid=\"signup-button\"]"
    ],
    [
        "nav a",
        "header a",
        "[role=\"navigation\"] a"
    ],
    [
        "button[type=\"submit\"]",
        ".cta-button",
        "[data-testid=\"primary-action\"]"
    ],
    [
        "[href*=\"dashboard\"]",
        "[href*=\"billing\"]",
        "[href*=\"settings\"]"
    ],
    [
        "[data-testid=\"add-to-cart\"]",
        "[data-testid=\"checkout\"]",
        "[data-testid=\"pay\"]"
    ]
];
    
    for (const path of clickPaths) {
      for (const selector of path) {
        try {
          await page.waitForSelector(selector, { timeout: 5000 });
          await page.click(selector);
          
          replay.push({
            timestamp: Date.now(),
            type: 'action',
            data: { type: 'click', selector },
            detections: []
          });
          
          // Wait for network activity to settle
          await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
        } catch (e) {
          // Selector not found, skip
        }
      }
    }
    
    // Save results
    const result = {
      verdict: detections.length > 0 ? 'fake' : 'real',
      score: Math.max(0, 100 - detections.length * 10),
      detections,
      replay,
      summary: {
        totalRequests: replay.filter(r => r.type === 'request').length,
        fakeRequests: detections.filter(d => d.type === 'fake-domain').length,
        totalActions: replay.filter(r => r.type === 'action').length,
        criticalIssues: detections.length
      },
      timestamp: new Date().toISOString()
    };
    
    // Write results
    const outputDir = 'C:\\Users\\mevla\\OneDrive\\Desktop\\guardrail\\.guardrail-demo';
    await fs.promises.mkdir(outputDir, { recursive: true });
    await fs.promises.writeFile(
      path.join(outputDir, 'reality-mode-result.json'),
      JSON.stringify(result, null, 2)
    );
    
    // Generate human-readable report
    const report = generateReport(result);
    await fs.promises.writeFile(
      path.join(outputDir, 'reality-mode-report.txt'),
      report
    );
    
    // Fail if fake data detected
    expect(detections.length, `Found ${detections.length} fake data issues`).toBe(0);
  });
});

function generateReport(result: any): string {
  const lines: string[] = [];
  
  lines.push('╔══════════════════════════════════════════════════════════════╗');
  lines.push('║            🔍 Reality Mode Scan Results 🔍                   ║');
  lines.push('╚══════════════════════════════════════════════════════════════╝');
  lines.push('');
  
  if (result.verdict === 'real') {
    lines.push('✅ VERDICT: REAL - No fake data detected!');
    lines.push('');
    lines.push('   Your app is shipping real features.');
  } else {
    lines.push('❌ VERDICT: FAKE - Fake data detected!');
    lines.push('');
    lines.push(`   Found ${result.detections.length} issues that indicate fake/mock data.`);
    lines.push('');
    lines.push('─'.repeat(64));
    lines.push('');
    lines.push('DETECTIONS:');
    lines.push('');
    
    for (const detection of result.detections) {
      lines.push(`   ❌ ${detection.type.toUpperCase()}`);
      lines.push(`      URL: ${detection.url}`);
      lines.push(`      Evidence: ${detection.evidence}`);
      lines.push('');
    }
  }
  
  lines.push('─'.repeat(64));
  lines.push(`Score: ${result.score}/100`);
  lines.push(`Total requests intercepted: ${result.summary.totalRequests}`);
  lines.push(`Actions performed: ${result.summary.totalActions}`);
  lines.push(`Generated: ${result.timestamp}`);
  
  return lines.join('\n');
}
