export const mockDataProductionFAQ = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is mock data in production?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Mock data in production is when test-only fixtures, stubbed service responses, or simulated API behavior ships in a real deploy and is served to real users or downstream systems.",
      },
    },
    {
      "@type": "Question",
      name: "How does mock data reach production?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Mock data reaches production when mocks are valid code that compiles cleanly, tests validate shapes instead of real integrations, runtime configuration is missing and triggers fallbacks, or shared monorepo packages hide dev-only imports.",
      },
    },
    {
      "@type": "Question",
      name: "Why doesn't CI catch mock data?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "CI validates syntax and test expectations, but not runtime reality. Mocks are syntactically valid and pass tests, but fail in real environments. CI answers 'Does it compile?' while production needs 'Is it real?'",
      },
    },
    {
      "@type": "Question",
      name: "How do I prevent mock data in production?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Prevent mock data by adding a deploy gate that blocks builds containing mock libraries outside dev/test contexts, __mocks__, fixtures, fake, seed artifacts in production builds, or missing required env vars that force fallback behavior.",
      },
    },
  ],
};

export const aiCodeHallucinationFAQ = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is AI code hallucination?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "AI code hallucination is code generated by an LLM that appears valid but contains fabricated logic, APIs, or assumptions that fail at runtime.",
      },
    },
    {
      "@type": "Question",
      name: "Why is AI code hallucination dangerous?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "AI code hallucination is dangerous because it compiles and can pass shallow tests, it looks 'reasonable' so it survives review, and it often fails silently with fake fallbacks or plausible objects.",
      },
    },
    {
      "@type": "Question",
      name: "How do I detect AI code hallucinations?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Detect AI code hallucinations by looking for placeholder branches and 'temporary' stubs in production paths, imports that don't exist, hardcoded or generic data objects, and missing env vars that trigger fake fallbacks.",
      },
    },
    {
      "@type": "Question",
      name: "How do I prevent AI code hallucinations in production?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Prevent AI code hallucinations by using a gate that checks reality boundaries: endpoint wiring, auth coverage, required env vars, and mock/stub imports in production builds.",
      },
    },
  ],
};

export const ciPassedProdFailedFAQ = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "Why does CI pass but production fail?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "CI passes but production fails due to stubs that look real, mocked integration boundaries, missing configuration, dead routes and placeholders, unenforced auth/RBAC, or monorepo drift between frontend and backend.",
      },
    },
    {
      "@type": "Question",
      name: "What's the difference between CI and production?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "CI validates syntax and test expectations. Production exposes runtime truth: environment, wiring, auth, real APIs, real data, and real load. Passing CI is not proof of production readiness.",
      },
    },
    {
      "@type": "Question",
      name: "How do I add a reality gate to CI?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Add a reality gate that checks endpoint mapping between frontend and backend, auth coverage, mock/stub imports, unused or placeholder route handlers, and required env vars present.",
      },
    },
  ],
};
